make sure promtail is gone (#1893)
* make sure promtail is gone

also fix vecotr start exit on error

* fix ci

diff --git a/bins/packages/vector/files/zinit-vector.yaml b/bins/packages/vector/files/zinit-vector.yaml
--- a/bins/packages/vector/files/zinit-vector.yaml
+++ b/bins/packages/vector/files/zinit-vector.yaml
@@ -2,11 +2,28 @@
 # in its own process group
 exec: |
   sh -c '
+  set -e
   pkill vector
 
   export NODE=$(identityd -address)
   export FARM=$(identityd -farm)
   export NETWORK=$(identityd -net)
+
+  if [ "${NODE}" = "" ]; then
+    echo "can't get node id"
+    exit 1
+  fi
+
+  if [ "${FARM}" = "" ]; then
+    echo "can't get farm id"
+    exit 1
+  fi
+
+  if [ "${NETWORK}" = "" ]; then
+    echo "can't get farm id"
+    exit 1
+  fi
+
   exec vector -c /etc/vector/vector.yaml
   '
 log: stdout
